/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { Abi } from "abitype";
import MyContractAbi from "~~/Main.abi.json";
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  10143: {
    MyContract: {
      address: "0xd6D4911DE291C97E8bB53DA822Bf78C15c605983",
      abi: MyContractAbi as Abi,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
